name: when pull_request
on:
  pull_request:
   branches: []
jobs:
  build:
   runs-on: ubuntu-latest
   services:
     postgres:
       image: postgres
       ports:
         - 5432:5432
       env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: prisma-db
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        TZ: "Asia/Tokyo"
   env:
     DATABASE_URL: postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}:5432/prisma-db
   steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: yarn cache
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: npm
    - run: yarn
    - run: yarn build
    - run: yarn prisma migrate deploy --preview-feature
    - run: yarn prisma db seed --preview-feature
    - name: yarn unit test
      run: yarn test:unit
    # - name: yarn integration test
    #   run: yarn test:integration
