name: when pull_request
on:
  pull_request:
   branches: []
env:
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
jobs:
  build:
   runs-on: ubuntu-18.04
   strategy:
    matrix:
     node-version: [14.x]
   services:
     postgres:
       image: postgres
       ports:
         - 5432:5432
       env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_INITDB_ARGS: ${{ secrets.POSTGRES_INITDB_ARGS }}
        TZ: ${{ secrets.TZ }}
   steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: yarn cache ${{ matrix.node-version }}
      uses: bahmutov/npm-install@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: unit test
      run: yarn test:unit
    - name: echo
      run: echo "job finished."
